#!/usr/bin/env python
# -*- coding: utf-8 -*-

EVENT_SCREENSHOT = 1 << 1

EVENT_CLICK = 1 << 2
EVENT_SWIPE = 1 << 3
EVENT_TYPE = 1 << 4

EVENT_CLICK_IMAGE = 1 << 5
EVENT_ASSERT_EXISTS = 1 << 6

EVENT_ALL = EVENT_SCREENSHOT | EVENT_CLICK | EVENT_CLICK_IMAGE | EVENT_ASSERT_EXISTS | EVENT_SWIPE | EVENT_TYPE
